# Generated by Django 5.2.5 on 2026-02-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(default=0)),
                ('customers', models.IntegerField(default=0)),
                ('projects', models.IntegerField(default=1)),
                ('admin', models.IntegerField(default=80)),
            ],
        ),
    ]
